import assert from 'node:assert/strict';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import sharp from 'sharp';
import { Store, hash, RUN_LIFETIME_MS } from '../src/store.js';
import { transform } from '../src/operations.js';
import { redactEvidence, artifactUrl, runCapability, nativeSourceMessage, prepareAgentLink, completeAgentLink, agentLinkAuthorized, queueNativeTask, claimNativeTask, integrationStatus } from '../src/minds.js';
import { sourceURL, publicAddress, htmlText } from '../src/source.js';

const directory = resolve('work', `self-check-${randomUUID()}`);
let store = new Store(directory);
const pairing = prepareAgentLink(store), pairRequest = randomUUID();
assert.throws(() => completeAgentLink(store, { code: 'wrong', request_id: pairRequest }), { status: 401 });
const linked = completeAgentLink(store, { code: pairing, request_id: pairRequest });
const linkExpiry = store.setting('agent_link_expires');
store.setSetting('agent_link_expires', String(Date.now() - 1));
assert.equal(integrationStatus(store).tools_ready, false);
assert.equal(integrationStatus(store).workspace_linked, false);
assert.equal(agentLinkAuthorized(store, `Bearer ${linked.link_token}`), false);
store.setSetting('agent_link_expires', linkExpiry);
assert.deepEqual(completeAgentLink(store, { code: pairing, request_id: pairRequest }), linked);
assert.throws(() => completeAgentLink(store, { code: pairing, request_id: randomUUID() }), { status: 409 });
assert.equal(agentLinkAuthorized(store, undefined), false);
assert.equal(agentLinkAuthorized(store, 'Bearer wrong'), false);
assert.equal(redactEvidence(`${pairing} ${linked.link_token}`), '[redacted] [redacted]');
store.setSetting('agent_pair_expires', String(Date.now() - 1));
assert.throws(() => completeAgentLink(store, { code: pairing, request_id: pairRequest }), { status: 401 });
const capability = runCapability(store, 'case-a', 'run-a');
assert.notEqual(capability, runCapability(store, 'case-b', 'run-a'));
assert.notEqual(capability, runCapability(store, 'case-a', 'run-b'));
assert.equal(redactEvidence(`Authorization: Bearer ${capability}`), 'Authorization: Bearer [redacted]');
const ownerMessage = { senderType: 1, senderId: 'owner', fingerprint: 'source-message', messageText: 'Investigate https://example.com/puzzle.' };
assert.equal(nativeSourceMessage(ownerMessage, 'owner').url, 'https://example.com/puzzle');
assert.equal(nativeSourceMessage(ownerMessage, 'another-owner'), null);
assert.equal(nativeSourceMessage({ ...ownerMessage, senderType: 0 }, 'owner'), null);
assert.equal(nativeSourceMessage({ ...ownerMessage, messageText: 'RIDDLEMASTER_BACKEND run\nhttps://example.com/puzzle' }, 'owner'), null);
assert.equal(nativeSourceMessage({ ...ownerMessage, messageText: 'Check the selected idea. [Open investigation](http://127.0.0.1:4317/?case=abc)' }, 'owner'), null);
assert.equal(nativeSourceMessage({ ...ownerMessage, messageText: 'https://example.com/a https://example.com/b' }, 'owner').text, 'https://example.com/a https://example.com/b');
const c = store.createCase('Storage acceptance');
const stageId = c.current_stage_id;
const source = await store.upload(c.id, stageId, 'clue.txt', 'text/plain', Buffer.from('RVZJREVOQ0U='));
const originalHash = source.sha256;
const checkpoint = store.checkpoint(c.id, 'Before checks');
const transformParams = { stage_id: stageId, artifact_id: source.id, operation: 'base64', params: {} };
const request = randomUUID();
const call = (operation, params, requestId = randomUUID(), runId = null) => store.exclusive(() => store.call(c.id, runId, requestId, operation, { stage_id: stageId, ...params }));
const [first, retry] = await Promise.all([call('transform_artifact', transformParams, request), call('transform_artifact', transformParams, request)]);
assert.equal(first.text, 'EVIDENCE'); assert.deepEqual(retry, first); assert.equal(store.getCase(c.id).budgets.transforms_used, 1);
assert.equal(hash(store.file(source.id)), originalHash);
const root = (await call('record_hypothesis', { text: 'Base64 yields evidence', status: 'untested', artifact_ids: [first.artifact.id] })).hypothesis;
assert.equal(store.getCase(c.id).stages[0].hypotheses.length, 1);
store.selectHypothesis(c.id, root.id);
await call('record_hypothesis', { hypothesis_id: root.id, text: 'Base64 yields evidence', status: 'supported', artifact_ids: [first.artifact.id] });
assert.equal(store.getCase(c.id).hypothesis_tree[0].parent_id, null);
const child = (await call('record_hypothesis', { text: 'Check a possible answer', status: 'untested', artifact_ids: [first.artifact.id] })).hypothesis;
assert.equal(child.parent_id, root.id);
await call('check_candidate', { candidate: 'UNKNOWN' });
assert.equal(store.getCase(c.id).events.at(-1).result.verification, 'unverified');
store.confirmByPlayer(c.id, stageId, 'UNKNOWN');
assert.equal(store.getCase(c.id).stages[0].status, 'player_confirmed');
await call('restore_checkpoint', checkpoint);
assert.equal(store.getCase(c.id).stages[0].status, 'open');
assert.equal(store.getCase(c.id).budgets.transforms_used, 1);
assert.equal(store.getCase(c.id).attempts[0].used, 1);
assert.deepEqual(store.getCase(c.id).stages[0].artifact_ids, [source.id]);
assert.equal(store.getCase(c.id).stages[0].hypotheses.length, 0);
assert.equal(store.getCase(c.id).hypothesis_tree.length, 2);
assert.equal(store.getCase(c.id).artifacts.length, 2);
store.close(); store = new Store(directory);
assert.equal(store.getCase(c.id).budgets.transforms_used, 1);
assert.equal(store.getCase(c.id).attempts[0].used, 1);
store.selectHypothesis(c.id, child.id);
assert.equal(store.getCase(c.id).selected_hypothesis_id, child.id);
assert(store.getCase(c.id).stages[0].artifact_ids.includes(first.artifact.id));
assert.equal(store.getCase(c.id).budgets.transforms_used, 1);
assert.equal(store.getCase(c.id).attempts[0].used, 1);
assert.deepEqual(await call('transform_artifact', transformParams, request), first);
await assert.rejects(() => call('transform_artifact', { ...transformParams, operation: 'hex' }, request), { status: 409 });
const failed = await call('transform_artifact', { artifact_id: source.id, operation: 'not-an-operation', params: {} });
assert.equal(failed.status, 'failed'); assert.equal(store.getCase(c.id).budgets.transforms_used, 2);
for (let i = 2; i < 20; i++) assert.equal((await call('transform_artifact', transformParams)).status, 'ok');
await assert.rejects(() => call('transform_artifact', transformParams), { status: 429 });
assert.equal(store.getCase(c.id).budgets.transforms_remaining, 0);
await call('check_candidate', { candidate: 'SECOND' }); await call('check_candidate', { candidate: 'THIRD' });
await assert.rejects(() => call('check_candidate', { candidate: 'FOURTH' }), { status: 429 });
assert.equal(store.getCase(c.id).attempts[0].used, 3);
const run = store.newRun(c.id);
for (let i = 0; i < 30; i++) await call('get_case_state', {}, randomUUID(), run.id);
await assert.rejects(() => call('get_case_state', {}, randomUUID(), run.id), { status: 429 });
store.finishRun(run.id, 'acceptance_check');
const nativeRun = store.newRun(c.id, true), finishRequest = randomUUID();
store.setSetting(`native_alias:${c.id}`, 'webapp:acceptance');
queueNativeTask(store, nativeRun, 'Check this clue');
const claimed = claimNativeTask(store, {});
assert.equal(claimed.run_id, nativeRun.id);
assert.equal(claimed.capability, runCapability(store, c.id, nativeRun.id));
assert.equal(claimNativeTask(store, { case_id: c.id }).run_id, nativeRun.id);
assert.throws(() => claimNativeTask(store, { case_id: randomUUID() }), { status: 409 });
const nativeFinish = await call('finish_investigation', { summary: 'No independent oracle: answer remains unverified.' }, finishRequest, nativeRun.id);
assert.equal(nativeFinish.status, 'ok');
assert.equal(store.run(nativeRun.id).status, 'replied');
assert.throws(() => claimNativeTask(store, {}), { status: 409 });
assert.deepEqual(await call('finish_investigation', { summary: 'No independent oracle: answer remains unverified.' }, finishRequest, nativeRun.id), nativeFinish);
const expired = store.newRun(c.id, true);
store.db.prepare('UPDATE runs SET created=? WHERE id=?').run(new Date(Date.now() - RUN_LIFETIME_MS - 1000).toISOString(), expired.id);
assert.equal(store.getCase(c.id).runs.find(r => r.id === expired.id).status, 'timed_out');
await assert.rejects(() => call('get_case_state', {}, randomUUID(), expired.id), { status: 409 });
for (const address of ['127.0.0.1', '10.0.0.1', '169.254.169.254', '172.16.0.1', '192.168.1.1', '100.64.0.1', '198.18.0.1', '192.0.2.1', '203.0.113.1', '::1', '::ffff:127.0.0.1', 'fc00::1', '2001:db8::1']) assert.equal(publicAddress(address), false, address);
assert(publicAddress('1.1.1.1')); assert(publicAddress('2606:4700:4700::1111'));
for (const url of ['http://example.com/', 'https://localhost/', 'https://127.0.0.1/', 'https://[::1]/', 'https://user:pass@example.com/', 'https://example.com:8080/', 'https://host.internal/']) assert.throws(() => sourceURL(url));
assert.equal(sourceURL('https://example.com/puzzle#fragment').href, 'https://example.com/puzzle');
assert.equal(htmlText('<script>hidden()</script><p>Clue &amp; key &#65;</p><p>Next</p>'), 'Clue & key A\nNext');
assert.equal((await transform(Buffer.from('6869'), 'text/plain', 'hex')).buffer.toString(), 'hi');
assert.equal((await transform(Buffer.from('uryyb'), 'text/plain', 'caesar', { shift: 13 })).buffer.toString(), 'hello');
assert.equal((await transform(Buffer.from('.... .. / .-'), 'text/plain', 'morse')).buffer.toString(), 'HI A');
assert.equal((await transform(Buffer.from('030e070704'), 'text/plain', 'xor', { key: 'k' })).buffer.toString(), 'hello');
await assert.rejects(() => transform(Buffer.from('***'), 'text/plain', 'base64'));
const rgba = Buffer.from([24, 24, 24, 254, 24, 24, 24, 255]);
const png = await sharp(rgba, { raw: { width: 2, height: 1, channels: 4 } }).png().toBuffer();
const channel = await transform(png, 'image/png', 'png_channel', { channel: 'alpha' });
const pixels = await sharp(channel.buffer).raw().toBuffer();
assert(pixels.includes(0) && pixels.includes(255));
for (const op of ['invert', 'contrast']) assert.equal((await sharp((await transform(png, 'image/png', op)).buffer).metadata()).format, 'png');
const demoA = await store.createDemo('a'), demoB = await store.createDemo('b');
assert.notEqual(demoA.artifacts[0].sha256, demoB.artifacts[0].sha256);
assert(!JSON.stringify(store.mindState(demoA.id)).includes('answer_hash'));
assert.equal(demoA.stages.length, 2);
assert.equal(redactEvidence({ message: `https://example.test/media/id?token=${'a'.repeat(64)}` }).message, 'https://example.test/media/id?token=[redacted]');
assert(artifactUrl(store, demoA.artifacts[0], false).startsWith('/media/'));
store.close();
// Exercise the actual setup command with isolated SDK/storage boundaries; no external authoring.
const setupSource = readFileSync(resolve('scripts/minds-setup.js'), 'utf8').replace(/^import .*;\r?\n/gm, '');
async function setupRequest(skills, dataDirectory) {
  const messages = [], directories = [], setupProcess = { argv: ['node', 'minds-setup.js', 'skill'], exitCode: 0 };
  await runInNewContext(`(async () => { ${setupSource} })()`, {
    sdk: () => ({ listMinds: async () => [], listEquippedSkills: async () => skills, ensureConversation: async () => {}, getLatestHistoryFingerprint: async () => 'before', sendMessage: async value => messages.push(value) }),
    Store: class { constructor(directory) { directories.push(directory); } close() {} }, integrationStatus: () => ({ mind_id: 'own-mind', public_url: 'https://example.com' }), config: () => ({ RIDDLEMASTER_DATA_DIR: dataDirectory }),
    prepareAgentLink: () => 'one-time-code', readFileSync: () => 'English playbook', mkdirSync() {}, writeFileSync() {}, requireValue: (ok, message) => { if (!ok) throw new Error(message); },
    process: setupProcess, AbortSignal, console: { log() {}, error() {} }
  });
  return { messages, directories, failed: Boolean(setupProcess.exitCode) };
}
const cleanSetup = await setupRequest([], 'custom-data');
assert.deepEqual(cleanSetup.directories, ['custom-data']);
assert.equal(cleanSetup.failed, false);
assert.equal(cleanSetup.messages.length, 1);
assert.equal(cleanSetup.messages[0].alias, 'riddlemaster-setup-own-mind');
assert.match(cleanSetup.messages[0].messageText, /Create and equip one PRIVATE investigation Skill/);
assert.match(cleanSetup.messages[0].messageText, /Do not publish/);
const otherSkill = { skillId: 'other-skill', name: 'Other', source: 'mind' }, ownSkill = { skillId: 'own-skill', name: 'Riddlemaster', source: 'mind' };
const existingSetup = await setupRequest([otherSkill, ownSkill]);
assert.deepEqual(existingSetup.directories, ['data']);
assert.match(existingSetup.messages[0].messageText, /existing PRIVATE Riddlemaster Skill own-skill/);
assert(!existingSetup.messages[0].messageText.includes('other-skill'));
assert(!/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/i.test(existingSetup.messages[0].messageText));
const ambiguousSetup = await setupRequest([ownSkill, { ...ownSkill, skillId: 'second-skill' }]);
assert.equal(ambiguousSetup.failed, true);
assert.equal(ambiguousSetup.messages.length, 0);
console.log(JSON.stringify({ status: 'passed', check: 'limited storage/operation acceptance', directory, assertions: ['immutable originals', 'idempotent retry', 'restore retains attempts/history', 'hypothesis snapshots and parent links survive restore/restart', 'native finish and run expiry', 'expired workspace link is not ready', 'setup discovers owner-specific Skill or requests a private one; ambiguous matches rejected', 'public source URL/IP boundaries and text extraction', 'restart persistence', 'failed attempt retained', 'transform/candidate/run limits', 'unknown oracle and player attribution', 'listed text/PNG operations', 'fresh two-stage fixtures', 'oracle isolation'], minds_integration: 'not exercised' }, null, 2));
